addPage('TAG_A.html,anchor <SMALL>(a)</SMALL>,a:hyperlink:anchor:position:url:target')
addPage('TAG_ABBR.html,abbreviation <SMALL>(abbr)</SMALL>,abbr:abbreviation')
addPage('TAG_ACRONYM.html,acronym <SMALL>(acronym)</SMALL>,acronym')
addPage('TAG_ADDRESS.html,address <SMALL>(address)</SMALL>,address')
addPage('TAG_APPLET.html,Java applet <SMALL>(applet)</SMALL>,applet:java:embed:param:alternative')
addPage('TAG_AREA.html,image-map area <SMALL>(area)</SMALL>,area:image:map:client:side:link:url:hyperlink:img:usemap')
addPage('TAG_AUDIOSCOPE.html,audioscope <SMALL>(audioscope)</SMALL>,audioscope:sound:amplitude:music:stereo')
addPage('TAG_B.html,bold <SMALL>(b)</SMALL>,b:bold')
addPage('TAG_BASE.html,document address <SMALL>(base)</SMALL>,base:url:address')
addPage('TAG_BASEFONT.html,default font <SMALL>(basefont)</SMALL>,basefont:defult:font')
addPage('TAG_BDO.html,bidirectional override <SMALL>(bdo)</SMALL>,bdo:direction:bidirectional:algorithm:ltr:rtl')
addPage('TAG_BGSOUND.html,background sound <SMALL>(bgsound)</SMALL>,bgsound:background:sound:music:midi:wav')
addPage('TAG_BIG.html,big <SMALL>(big)</SMALL>,big:font:size')
addPage('TAG_BLACKFACE.html,blackface <SMALL>(blackface)</SMALL>,blackface:double:bold:font')
addPage('TAG_BLINK.html,blink <SMALL>(blink)</SMALL>,blink:text')
addPage('TAG_BLOCKQUOTE.html,block quotations <SMALL>(blockquote)</SMALL>,blockquote:quote:bq:cite')
addPage('TAG_BODY.html,body section <SMALL>(body)</SMALL>,body:main:section:visible:color:background')
addPage('TAG_BQ.html,block quotations <SMALL>(bq)</SMALL>,bq:quote:blockquote:cite')
addPage('TAG_BR.html,line break <SMALL>(br)</SMALL>,br:line:break')
addPage('TAG_BUTTON.html,button <SMALL>(button)</SMALL>,button:form')
addPage('TAG_CAPTION.html,table caption <SMALL>(caption)</SMALL>,caption:table')
addPage('TAG_CENTER.html,center <SMALL>(center)</SMALL>,center:div:align')
addPage('TAG_CITE.html,citation <SMALL>(cite)</SMALL>,cite:quote:blockquote:bq')
addPage('TAG_CODE.html,code example <SMALL>(code)</SMALL>,code:source:example:listing:pre')
addPage('TAG_COL.html,column properties <SMALL>(col)</SMALL>,col:table:column:settings:alignment:colgroup')
addPage('TAG_COLGROUP.html,column definition <SMALL>(colgroup)</SMALL>,colgroup:table:column:settings:col:alignment')
addPage('TAG_COMMENT.html,comment <SMALL>(comment)</SMALL>,comment:!--')
addPage('TAG_DD.html,definition description <SMALL>(dd)</SMALL>,dd:dl:definition:list:description:dt:term')
addPage('TAG_DEL.html,deleted text <SMALL>(del)</SMALL>,del:deleted:text:original:replace')
addPage('TAG_DFN.html,definition <SMALL>(dfn)</SMALL>,dfn:definition:text')
addPage('TAG_DIR.html,directory list <SMALL>(dir)</SMALL>,dir:directory:list:menu:ul')
addPage('TAG_DIV.html,division <SMALL>(div)</SMALL>,div:division:center:alignment:float')
addPage('TAG_DL.html,definition list <SMALL>(dl)</SMALL>,dl:definition:list:dt:term:dd:description')
addPage('TAG_DT.html,definition term <SMALL>(dt)</SMALL>,dt:definition:term:dl:list:dd:description')
addPage('TAG_EM.html,emphasis <SMALL>(em)</SMALL>,em:emphasis:strong')
addPage('TAG_EMBED.html,embed object <SMALL>(embed)</SMALL>,embed:plug:in:applet:java:parameter:sound:music:midi:wav')
addPage('TAG_FIELDSET.html,form control group <SMALL>(fieldset)</SMALL>,fieldset:group:form:control:tabbing:order:legend:caption')
addPage('TAG_FN.html,footnote <SMALL>(fn)</SMALL>,fn:footnote')
addPage('TAG_FONT.html,font <SMALL>(font)</SMALL>,font:text:size:color')
addPage('TAG_FORM.html,form <SMALL>(form)</SMALL>,form:field:input:submit:radio:button:checkbox:textarea:get:post')
addPage('TAG_FRAME.html,frame <SMALL>(frame)</SMALL>,frame:divide:window:section:frameset:border')
addPage('TAG_FRAMESET.html,frame contents <SMALL>(frameset)</SMALL>,frameset:divide:window:border')
addPage('TAG_H1.html,header <SMALL>(h1)</SMALL>,h1:header:size')
addPage('TAG_H2.html,header <SMALL>(h2)</SMALL>,h2:header:size')
addPage('TAG_H3.html,header <SMALL>(h3)</SMALL>,h3:header:size')
addPage('TAG_H4.html,header <SMALL>(h4)</SMALL>,h4:header:size')
addPage('TAG_H5.html,header <SMALL>(h5)</SMALL>,h5:header:size')
addPage('TAG_H6.html,header <SMALL>(h6)</SMALL>,h6:header:size')
addPage('TAG_HEAD.html,head section <SMALL>(head)</SMALL>,head:section:page:title:meta:script:style:sheet:search:engine')
addPage('TAG_HR.html,horizontal rule <SMALL>(hr)</SMALL>,hr:horizontal:ruler:divider')
addPage('TAG_HTML.html,www document <SMALL>(html)</SMALL>,html:page:version:www:document:top')
addPage('TAG_I.html,italic <SMALL>(i)</SMALL>,i:italic:text')
addPage('TAG_IFRAME.html,inline frame <SMALL>(iframe)</SMALL>,iframe:inline:frame')
addPage('TAG_ILAYER.html,inline layer <SMALL>(ilayer)</SMALL>,ilayer:inline:layer:absolute:position')
addPage('TAG_IMG.html,image <SMALL>(img)</SMALL>,img:image:map:area:client:side:server:side:mouse:over:change:graphic:picture:photo:alternative:border')
addPage('TAG_INPUT.html,input field <SMALL>(input)</SMALL>,input:form:control:field:radio:button:checkbox:submit')
addPage('TAG_INS.html,inserted text <SMALL>(ins)</SMALL>,ins:insert:text:replace')
addPage('TAG_ISINDEX.html,search field <SMALL>(isindex)</SMALL>,isindex:input:field:submit:server:url')
addPage('TAG_KBD.html,keyboard <SMALL>(kbd)</SMALL>,kbd:keyboard:entry:text')
addPage('TAG_KEYGEN.html,generate key <SMALL>(keygen)</SMALL>,keygen:encryption:server:generate:key:certificate:public')
addPage('TAG_LABEL.html,field label <SMALL>(label)</SMALL>,label:form:field:label')
addPage('TAG_LAYER.html,layer <SMALL>(layer)</SMALL>,layer:layer:absolute:position')
addPage('TAG_LEGEND.html,fieldset caption <SMALL>(legend)</SMALL>,legend:form:fieldset:controls:caption')
addPage('TAG_LI.html,list item <SMALL>(li)</SMALL>,li:list:item:ul:ol:dir:menu')
addPage('TAG_LIMITTEXT.html,text width <SMALL>(limittext)</SMALL>,limittext:maximum:width:text')
addPage('TAG_LINK.html,link <SMALL>(link)</SMALL>,link:resource:head:style:sheet:css')
addPage('TAG_LISTING.html,program listing <SMALL>(listing)</SMALL>,listing:program:source:listing:spacing:pre')
addPage('TAG_MAP.html,image-map <SMALL>(map)</SMALL>,map:client:side:image:map:area:img')
addPage('TAG_MARQUEE.html,scrolling text <SMALL>(marquee)</SMALL>,marquee:scrolling:text')
addPage('TAG_MENU.html,menu listing <SMALL>(menu)</SMALL>,menu:list:items')
addPage('TAG_META.html,meta information <SMALL>(meta)</SMALL>,meta:document:information:search:engine:redirect:language:encoding:http:header:cache:expiration:refresh:keywords')
addPage('TAG_MULTICOL.html,multiple columns <SMALL>(multicol)</SMALL>,multicol:multiple:columns:newspaper')
addPage('TAG_NOBR.html,no line break <SMALL>(nobr)</SMALL>,nobr:no:line:break:wbr')
addPage('TAG_NOEMBED.html,embed alternative <SMALL>(noembed)</SMALL>,noembed:alternative:embed:plugin')
addPage('TAG_NOFRAMES.html,frame alternative <SMALL>(noframes)</SMALL>,noframes:alternative:frames:support')
addPage('TAG_NOSCRIPT.html,script alternative <SMALL>(noscript)</SMALL>,noscript:alternative:script')
addPage('TAG_NOSMARTQUOTES.html,quote style <SMALL>(nosmartquotes)</SMALL>,nosmartquotes:style:quotes')
addPage('TAG_OBJECT.html,object <SMALL>(object)</SMALL>,object:embed:parameter:plugin:java:vrml:sound:music')
addPage('TAG_OL.html,ordered list <SMALL>(ol)</SMALL>,ol:ordered:list:numbered:ul')
addPage('TAG_OPTGROUP.html,option group <SMALL>(optgroup)</SMALL>,optgroup:group:options:selection:list:form:field')
addPage('TAG_OPTION.html,listbox option <SMALL>(option)</SMALL>,option:selection:list:option:form:menu:choice')
addPage('TAG_P.html,paragraph <SMALL>(p)</SMALL>,p:text:paragraph:division:part')
addPage('TAG_PARAM.html,object parameter <SMALL>(param)</SMALL>,param:applet:parameter:java:object')
addPage('TAG_PLAINTEXT.html,ignore tags <SMALL>(plaintext)</SMALL>,plaintext:text:ignore:tag:element')
addPage('TAG_PRE.html,preformatted text <SMALL>(pre)</SMALL>,pre:preformatted:text:spacing:listing:code:source:whitespace')
addPage('TAG_Q.html,short quotations <SMALL>(q)</SMALL>,q:quote:quotation:cite:citation:blockquote')
addPage('TAG_S.html,strikethrough <SMALL>(s)</SMALL>,s:strikethough:text:replaced:text:deleted:inserted')
addPage('TAG_SAMP.html,output sample <SMALL>(samp)</SMALL>,samp:sample:text:program:output')
addPage('TAG_SCRIPT.html,browser scripting <SMALL>(script)</SMALL>,script:programming:language:javascript:jscript:vbscript:!--')
addPage('TAG_SELECT.html,listbox input <SMALL>(select)</SMALL>,select:form:field:selection:list:option:menu')
addPage('TAG_SERVER.html,server-side script <SMALL>(server)</SMALL>,server:script:http')
addPage('TAG_SHADOW.html,shadow <SMALL>(shadow)</SMALL>,shadow')
addPage('TAG_SIDEBAR.html,sidebar <SMALL>(sidebar)</SMALL>,sidebar')
addPage('TAG_SMALL.html,small <SMALL>(small)</SMALL>,small:font:size:big')
addPage('TAG_SPACER.html,whitespace <SMALL>(spacer)</SMALL>,spacer:whitespace:single:pixel:gif:layout')
addPage('TAG_SPAN.html,style sheet <SMALL>(span)</SMALL>,span:structure:document:style:sheet:div')
addPage('TAG_STRIKE.html,strikethrough <SMALL>(strike)</SMALL>,strike:strikethough:text:replaced:text:deleted:inserted')
addPage('TAG_STRONG.html,strong emphasis <SMALL>(strong)</SMALL>,strong:bold:strong:emphasis')
addPage('TAG_STYLE.html,style sheet <SMALL>(style)</SMALL>,style:sheet:css:head:!--:link:presentation')
addPage('TAG_SUB.html,subscript <SMALL>(sub)</SMALL>,sub:subscript')
addPage('TAG_SUP.html,superscript <SMALL>(sup)</SMALL>,sup:superscript')
addPage('TAG_TABLE.html,table <SMALL>(table)</SMALL>,table:row:column:spreadsheet:tr:td:th:caption:thead:tbody:tfoot:col:colgroup:layout:border')
addPage('TAG_TBODY.html,table body <SMALL>(tbody)</SMALL>,tbody:table:body:cell')
addPage('TAG_TD.html,table data <SMALL>(td)</SMALL>,td:table:data:cell')
addPage('TAG_TEXTAREA.html,textarea input <SMALL>(textarea)</SMALL>,textarea:form:field:text:area')
addPage('TAG_TFOOT.html,table footer <SMALL>(tfoot)</SMALL>,tfoot:table:footer:cell')
addPage('TAG_TH.html,table header <SMALL>(th)</SMALL>,th:table:header:cell')
addPage('TAG_THEAD.html,table header <SMALL>(thead)</SMALL>,thead:table:header:cell')
addPage('TAG_TITLE.html,document title <SMALL>(title)</SMALL>,title:document:head')
addPage('TAG_TR.html,table row <SMALL>(tr)</SMALL>,tr:table:row')
addPage('TAG_TT.html,teletype <SMALL>(tt)</SMALL>,tt:teletype:text:monospaced')
addPage('TAG_U.html,underline <SMALL>(u)</SMALL>,u:underline:text')
addPage('TAG_UL.html,unordered list <SMALL>(ul)</SMALL>,ul:unordered:list:item:ol:li:dl')
addPage('TAG_VAR.html,variable <SMALL>(var)</SMALL>,var:describe:variable')
addPage('TAG_WBR.html,word break <SMALL>(wbr)</SMALL>,wbr:word:break:nobr:line:br')
addPage('TAG_XMP.html,fixed width <SMALL>(xmp)</SMALL>,xmp:example')
addPage('TAG__COMMENT.html,comment <SMALL>(!--)</SMALL>,!--:comment:source:script:style:sheet:css')
addPage('TAG__DOCTYPE.html,html version <SMALL>(!doctype)</SMALL>,doctype:dtd:version:validate:strict:transitional:frameset:sgml:html')
addPage('color.html,How to use color in HTML-pages,HTML:reference:color:palette')
addPage('colornames.html,Defined colornames,HTML:reference:color:colornames:palette')
addPage('palette.html,Specification of the fixed Netscape palette,HTML:reference:palette:color')
addPage('characters.html,The character set and special characters,HTML:reference:character:set:lang:special:entity:entities:unicode:accent:symbol')
addPage('download.html,Download the HTML Tag List,download:zip:site:save:mirror:tar')
addPage('history.html,History of the HTML Tag List,version:history:changes:log')
addPage('askme.html,Form to ask me questions about HTML,ask:question')
addPage('legal.html,Legal terms about the usage of the HTML Tag List,legal:terms:mirror:download:usage:copyright')
addPage('awards.html,Awards and related stuff,award:price:articles')
addPage('faq.html,FAQ, Tips & Tricks,faq:tips:tricks:questions:answers:scripts')
addPage('faq1.html,What does the &amp;nbsp; character mean?,&nbsp;')
addPage('faq2.html,How do I load a page in another frame?,frame:target:link:redirect:load')
addPage('faq3.html,How do I use an image to submit a form?,image:submit:form')
addPage('faq4.html,How do you create a background sound?,background:sound:music:play:midi:wav')
addPage('faq6.html,Can I protect my pages from being framed by someone else?,protect:framed:other:site')
addPage('faq8.html,Why has the last line on my page has an open space above it?,last:line:space:above:font:size')
addPage('faq9.html,How can I maintain the layout of my frames?,frameset:layout:restore:frameset')
addPage('faq11.html,How can I automatically redirect the user to another page?,redirect:user:automatically:other:page:meta:http-equiv:refresh')
addPage('faq12.html,How can I change two or more pages when a link is clicked?,change:two:pages:one:click:target:frameset')
addPage('generic_attributes.html,Generic_attributes,accesskey:class:dir:id:lang:onblur:onclick:ondblclick:onfocus:onkey:onmouse:tabindex:title:language:tabbing order')
addPage('css.html,Introduction to Cascading Style Sheets,style:sheets:css:layout:presentation:style:class:link:properties')
addPage('resources.html,Searchable directory with HTML related resources,resources:scripts:w3c:recommendations:newsgroups:mailing:list')
addPage('faq5.html,How can I change an image when the mouse moves over it?,change:image:mouse:over')
addPage('faq7.html,How can I password-protect a HTML page?,protect:page:password:security:restrict:access')
addPage('faq10.hmtl,How can I change the color of a link?,color:link:change:css:style:sheet')
addPage('faq13.html,How can I open a new browser window from a link?,open:browser:window:link')
addPage('faq14.html,How can I make text scroll in the status bar?,scrolling:text:status:bar')
